services:
  turbopix:
    build:
      context: .
      dockerfile: container-data/Containerfile
    ports:
      - "18473:18473"
    volumes:
      - ./data:/data
      - ./photos:/photos:ro
    environment:
      - RUST_LOG=info
    restart: unless-stopped