name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Check format
      run: cargo fmt --all -- --check

    - name: Run linter
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test

    - name: Build release
      run: cargo build --release